
package App::Asciio::Cross ;

$|++ ;

use strict;
use warnings;
use utf8;

use Clone;

use Readonly ;
use List::Util qw(first) ;
use List::MoreUtils qw(any) ;

#-----------------------------------------------------------------------------

use constant {
	UP_OFFSET    => 0,
	DOWN_OFFSET  => 3,
	LEFT_OFFSET  => 6,
	RIGHT_OFFSET => 9,
	D45_OFFSET   => 12,
	D135_OFFSET  => 15,
	D225_OFFSET  => 18,
	D315_OFFSET  => 21,
	
	ATTR_MASK => 7,
	NONE      => 0,
	ASCI      => 1,
	THIN      => 2,
	BOLD      => 3,
	DOBL      => 4,
	DOTT      => 5,
	BDOT      => 6,
	} ;

#-----------------------------------------------------------------------------

#                        right  d45   up    d135  left  d225  down  d315
Readonly my %CROSS_CHARS_VALUES =>
	(
	')' => make_char_mask(ASCI, NONE, ASCI, NONE, ASCI, NONE, ASCI, NONE),
	'┌' => make_char_mask(THIN, NONE, NONE, NONE, NONE, NONE, THIN, NONE),
	'└' => make_char_mask(THIN, NONE, THIN, NONE, NONE, NONE, NONE, NONE),
	'┘' => make_char_mask(NONE, NONE, THIN, NONE, THIN, NONE, NONE, NONE),
	'┐' => make_char_mask(NONE, NONE, NONE, NONE, THIN, NONE, THIN, NONE),
	'-' => make_char_mask(ASCI, NONE, NONE, NONE, ASCI, NONE, NONE, NONE),
	'|' => make_char_mask(NONE, NONE, ASCI, NONE, NONE, NONE, ASCI, NONE),
	'+' => make_char_mask(ASCI, NONE, ASCI, NONE, ASCI, NONE, ASCI, NONE),
	'X' => make_char_mask(NONE, ASCI, NONE, ASCI, NONE, ASCI, NONE, ASCI),
	'.' => make_char_mask(ASCI, NONE, NONE, NONE, ASCI, NONE, ASCI, NONE),
	"'" => make_char_mask(ASCI, NONE, ASCI, NONE, ASCI, NONE, NONE, NONE),
	'^' => make_char_mask(NONE, NONE, NONE, NONE, NONE, NONE, ASCI, NONE),
	'>' => make_char_mask(NONE, NONE, NONE, NONE, ASCI, NONE, NONE, NONE),
	'v' => make_char_mask(NONE, NONE, ASCI, NONE, NONE, NONE, NONE, NONE),
	'<' => make_char_mask(ASCI, NONE, NONE, NONE, NONE, NONE, NONE, NONE),
	'/' => make_char_mask(NONE, ASCI, NONE, NONE, NONE, ASCI, NONE, NONE),
	'\\'=> make_char_mask(NONE, NONE, NONE, ASCI, NONE, NONE, NONE, ASCI),
	'⟨' => make_char_mask(THIN, THIN, NONE, NONE, NONE, NONE, NONE, THIN),
	'⟩' => make_char_mask(NONE, NONE, NONE, THIN, THIN, THIN, NONE, NONE),
	'˄' => make_char_mask(NONE, NONE, NONE, NONE, NONE, THIN, THIN, THIN),
	'˅' => make_char_mask(NONE, THIN, THIN, THIN, NONE, NONE, NONE, NONE),
	'▲' => make_char_mask(NONE, NONE, NONE, NONE, NONE, BOLD, BOLD, BOLD),
	'▼' => make_char_mask(NONE, BOLD, BOLD, BOLD, NONE, NONE, NONE, NONE),
	'◀' => make_char_mask(BOLD, BOLD, NONE, NONE, NONE, NONE, NONE, BOLD),
	'▶' => make_char_mask(NONE, NONE, NONE, BOLD, BOLD, BOLD, NONE, NONE),
	'△' => make_char_mask(NONE, NONE, NONE, NONE, NONE, DOBL, DOBL, DOBL),
	'▽' => make_char_mask(NONE, DOBL, DOBL, DOBL, NONE, NONE, NONE, NONE),
	'◁' => make_char_mask(DOBL, DOBL, NONE, NONE, NONE, NONE, NONE, DOBL),
	'▷' => make_char_mask(NONE, NONE, NONE, DOBL, DOBL, DOBL, NONE, NONE),
	'─' => make_char_mask(THIN, NONE, NONE, NONE, THIN, NONE, NONE, NONE),
	'│' => make_char_mask(NONE, NONE, THIN, NONE, NONE, NONE, THIN, NONE),
	'━' => make_char_mask(BOLD, NONE, NONE, NONE, BOLD, NONE, NONE, NONE),
	'┃' => make_char_mask(NONE, NONE, BOLD, NONE, NONE, NONE, BOLD, NONE),
	'═' => make_char_mask(DOBL, NONE, NONE, NONE, DOBL, NONE, NONE, NONE),
	'║' => make_char_mask(NONE, NONE, DOBL, NONE, NONE, NONE, DOBL, NONE),
	'╱' => make_char_mask(NONE, THIN, NONE, NONE, NONE, THIN, NONE, NONE),
	'╲' => make_char_mask(NONE, NONE, NONE, THIN, NONE, NONE, NONE, THIN),
	'┄' => make_char_mask(DOTT, NONE, NONE, NONE, DOTT, NONE, NONE, NONE),
	'┆' => make_char_mask(NONE, NONE, DOTT, NONE, NONE, NONE, DOTT, NONE),
	'┅' => make_char_mask(BDOT, NONE, NONE, NONE, BDOT, NONE, NONE, NONE),
	'┇' => make_char_mask(NONE, NONE, BDOT, NONE, NONE, NONE, BDOT, NONE),
	'┽' => make_char_mask(THIN, NONE, THIN, NONE, BOLD, NONE, THIN, NONE),
	'┾' => make_char_mask(BOLD, NONE, THIN, NONE, THIN, NONE, THIN, NONE),
	'┿' => make_char_mask(BOLD, NONE, THIN, NONE, BOLD, NONE, THIN, NONE),
	'╀' => make_char_mask(THIN, NONE, BOLD, NONE, THIN, NONE, THIN, NONE),
	'╁' => make_char_mask(THIN, NONE, THIN, NONE, THIN, NONE, BOLD, NONE),
	'╂' => make_char_mask(THIN, NONE, BOLD, NONE, THIN, NONE, BOLD, NONE),
	'╃' => make_char_mask(THIN, NONE, BOLD, NONE, BOLD, NONE, THIN, NONE),
	'╄' => make_char_mask(BOLD, NONE, BOLD, NONE, THIN, NONE, THIN, NONE),
	'╅' => make_char_mask(THIN, NONE, THIN, NONE, BOLD, NONE, BOLD, NONE),
	'╆' => make_char_mask(BOLD, NONE, THIN, NONE, THIN, NONE, BOLD, NONE),
	'╇' => make_char_mask(BOLD, NONE, BOLD, NONE, BOLD, NONE, THIN, NONE),
	'╈' => make_char_mask(BOLD, NONE, THIN, NONE, BOLD, NONE, BOLD, NONE),
	'╉' => make_char_mask(THIN, NONE, BOLD, NONE, BOLD, NONE, BOLD, NONE),
	'╊' => make_char_mask(BOLD, NONE, BOLD, NONE, THIN, NONE, BOLD, NONE),
	'╫' => make_char_mask(THIN, NONE, DOBL, NONE, THIN, NONE, DOBL, NONE),
	'╪' => make_char_mask(DOBL, NONE, THIN, NONE, DOBL, NONE, THIN, NONE),
	'┼' => make_char_mask(THIN, NONE, THIN, NONE, THIN, NONE, THIN, NONE),
	'╋' => make_char_mask(BOLD, NONE, BOLD, NONE, BOLD, NONE, BOLD, NONE),
	'╬' => make_char_mask(DOBL, NONE, DOBL, NONE, DOBL, NONE, DOBL, NONE),
	'┵' => make_char_mask(THIN, NONE, THIN, NONE, BOLD, NONE, NONE, NONE),
	'┶' => make_char_mask(BOLD, NONE, THIN, NONE, THIN, NONE, NONE, NONE),
	'┷' => make_char_mask(BOLD, NONE, THIN, NONE, BOLD, NONE, NONE, NONE),
	'┸' => make_char_mask(THIN, NONE, BOLD, NONE, THIN, NONE, NONE, NONE),
	'┹' => make_char_mask(THIN, NONE, BOLD, NONE, BOLD, NONE, NONE, NONE),
	'┺' => make_char_mask(BOLD, NONE, BOLD, NONE, THIN, NONE, NONE, NONE),
	'┭' => make_char_mask(THIN, NONE, NONE, NONE, BOLD, NONE, THIN, NONE),
	'┮' => make_char_mask(BOLD, NONE, NONE, NONE, THIN, NONE, THIN, NONE),
	'┯' => make_char_mask(BOLD, NONE, NONE, NONE, BOLD, NONE, THIN, NONE),
	'┰' => make_char_mask(THIN, NONE, NONE, NONE, THIN, NONE, BOLD, NONE),
	'┱' => make_char_mask(THIN, NONE, NONE, NONE, BOLD, NONE, BOLD, NONE),
	'┲' => make_char_mask(BOLD, NONE, NONE, NONE, THIN, NONE, BOLD, NONE),
	'┥' => make_char_mask(NONE, NONE, THIN, NONE, BOLD, NONE, THIN, NONE),
	'┦' => make_char_mask(NONE, NONE, BOLD, NONE, THIN, NONE, THIN, NONE),
	'┧' => make_char_mask(NONE, NONE, THIN, NONE, THIN, NONE, BOLD, NONE),
	'┨' => make_char_mask(NONE, NONE, BOLD, NONE, THIN, NONE, BOLD, NONE),
	'┩' => make_char_mask(NONE, NONE, BOLD, NONE, BOLD, NONE, THIN, NONE),
	'┪' => make_char_mask(NONE, NONE, THIN, NONE, BOLD, NONE, BOLD, NONE),
	'┝' => make_char_mask(BOLD, NONE, THIN, NONE, NONE, NONE, THIN, NONE),
	'┞' => make_char_mask(THIN, NONE, BOLD, NONE, NONE, NONE, THIN, NONE),
	'┟' => make_char_mask(THIN, NONE, THIN, NONE, NONE, NONE, BOLD, NONE),
	'┠' => make_char_mask(THIN, NONE, BOLD, NONE, NONE, NONE, BOLD, NONE),
	'┡' => make_char_mask(BOLD, NONE, BOLD, NONE, NONE, NONE, THIN, NONE),
	'┢' => make_char_mask(BOLD, NONE, THIN, NONE, NONE, NONE, BOLD, NONE),
	'╨' => make_char_mask(THIN, NONE, DOBL, NONE, THIN, NONE, NONE, NONE),
	'╧' => make_char_mask(DOBL, NONE, THIN, NONE, DOBL, NONE, NONE, NONE),
	'╥' => make_char_mask(THIN, NONE, NONE, NONE, THIN, NONE, DOBL, NONE),
	'╤' => make_char_mask(DOBL, NONE, NONE, NONE, DOBL, NONE, THIN, NONE),
	'╢' => make_char_mask(NONE, NONE, DOBL, NONE, THIN, NONE, DOBL, NONE),
	'╡' => make_char_mask(NONE, NONE, THIN, NONE, DOBL, NONE, THIN, NONE),
	'╟' => make_char_mask(THIN, NONE, DOBL, NONE, NONE, NONE, DOBL, NONE),
	'╞' => make_char_mask(DOBL, NONE, THIN, NONE, NONE, NONE, THIN, NONE),
	'┤' => make_char_mask(NONE, NONE, THIN, NONE, THIN, NONE, THIN, NONE),
	'├' => make_char_mask(THIN, NONE, THIN, NONE, NONE, NONE, THIN, NONE),
	'┬' => make_char_mask(THIN, NONE, NONE, NONE, THIN, NONE, THIN, NONE),
	'┴' => make_char_mask(THIN, NONE, THIN, NONE, THIN, NONE, NONE, NONE),
	'┫' => make_char_mask(NONE, NONE, BOLD, NONE, BOLD, NONE, BOLD, NONE),
	'┣' => make_char_mask(BOLD, NONE, BOLD, NONE, NONE, NONE, BOLD, NONE),
	'┳' => make_char_mask(BOLD, NONE, NONE, NONE, BOLD, NONE, BOLD, NONE),
	'┻' => make_char_mask(BOLD, NONE, BOLD, NONE, BOLD, NONE, NONE, NONE),
	'╣' => make_char_mask(NONE, NONE, DOBL, NONE, DOBL, NONE, DOBL, NONE),
	'╠' => make_char_mask(DOBL, NONE, DOBL, NONE, NONE, NONE, DOBL, NONE),
	'╦' => make_char_mask(DOBL, NONE, NONE, NONE, DOBL, NONE, DOBL, NONE),
	'╩' => make_char_mask(DOBL, NONE, DOBL, NONE, DOBL, NONE, NONE, NONE),
	'╜' => make_char_mask(NONE, NONE, DOBL, NONE, THIN, NONE, NONE, NONE),
	'╛' => make_char_mask(NONE, NONE, THIN, NONE, DOBL, NONE, NONE, NONE),
	'╙' => make_char_mask(THIN, NONE, DOBL, NONE, NONE, NONE, NONE, NONE),
	'╘' => make_char_mask(DOBL, NONE, THIN, NONE, NONE, NONE, NONE, NONE),
	'╖' => make_char_mask(NONE, NONE, NONE, NONE, THIN, NONE, DOBL, NONE),
	'╕' => make_char_mask(NONE, NONE, NONE, NONE, DOBL, NONE, THIN, NONE),
	'╓' => make_char_mask(THIN, NONE, NONE, NONE, NONE, NONE, DOBL, NONE),
	'╒' => make_char_mask(DOBL, NONE, NONE, NONE, NONE, NONE, THIN, NONE),
	'┍' => make_char_mask(BOLD, NONE, NONE, NONE, NONE, NONE, THIN, NONE),
	'┎' => make_char_mask(THIN, NONE, NONE, NONE, NONE, NONE, BOLD, NONE),
	'┑' => make_char_mask(NONE, NONE, NONE, NONE, BOLD, NONE, THIN, NONE),
	'┒' => make_char_mask(NONE, NONE, NONE, NONE, THIN, NONE, BOLD, NONE),
	'┕' => make_char_mask(BOLD, NONE, THIN, NONE, NONE, NONE, NONE, NONE),
	'┖' => make_char_mask(THIN, NONE, BOLD, NONE, NONE, NONE, NONE, NONE),
	'┙' => make_char_mask(NONE, NONE, THIN, NONE, BOLD, NONE, NONE, NONE),
	'┚' => make_char_mask(NONE, NONE, BOLD, NONE, THIN, NONE, NONE, NONE),
	'╭' => make_char_mask(THIN, NONE, NONE, NONE, NONE, NONE, THIN, NONE),
	'╮' => make_char_mask(NONE, NONE, NONE, NONE, THIN, NONE, THIN, NONE),
	'╯' => make_char_mask(NONE, NONE, THIN, NONE, THIN, NONE, NONE, NONE),
	'╰' => make_char_mask(THIN, NONE, THIN, NONE, NONE, NONE, NONE, NONE),
	'┏' => make_char_mask(BOLD, NONE, NONE, NONE, NONE, NONE, BOLD, NONE),
	'┓' => make_char_mask(NONE, NONE, NONE, NONE, BOLD, NONE, BOLD, NONE),
	'┛' => make_char_mask(NONE, NONE, BOLD, NONE, BOLD, NONE, NONE, NONE),
	'┗' => make_char_mask(BOLD, NONE, BOLD, NONE, NONE, NONE, NONE, NONE),
	'╔' => make_char_mask(DOBL, NONE, NONE, NONE, NONE, NONE, DOBL, NONE),
	'╗' => make_char_mask(NONE, NONE, NONE, NONE, DOBL, NONE, DOBL, NONE),
	'╝' => make_char_mask(NONE, NONE, DOBL, NONE, DOBL, NONE, NONE, NONE),
	'╚' => make_char_mask(DOBL, NONE, DOBL, NONE, NONE, NONE, NONE, NONE),
	'╳' => make_char_mask(NONE, THIN, NONE, THIN, NONE, THIN, NONE, THIN),
	 ) ;

Readonly my %VALUES_TO_CROSS_CHAR =>
	(
	make_char_mask(ASCI, NONE, ASCI, NONE, ASCI, NONE, ASCI, NONE) => '+',
	make_char_mask(ASCI, NONE, NONE, NONE, ASCI, NONE, ASCI, NONE) => '.',
	make_char_mask(ASCI, NONE, NONE, NONE, NONE, NONE, ASCI, NONE) => '.',
	make_char_mask(NONE, NONE, NONE, NONE, ASCI, NONE, ASCI, NONE) => '.',
	make_char_mask(ASCI, NONE, ASCI, NONE, NONE, NONE, ASCI, NONE) => '.',
	make_char_mask(NONE, NONE, ASCI, NONE, ASCI, NONE, ASCI, NONE) => '.',
	make_char_mask(ASCI, NONE, ASCI, NONE, ASCI, NONE, NONE, NONE) => "'",
	make_char_mask(NONE, NONE, ASCI, NONE, ASCI, NONE, NONE, NONE) => "'",
	make_char_mask(ASCI, NONE, ASCI, NONE, NONE, NONE, NONE, NONE) => "'",
	make_char_mask(THIN, NONE, THIN, NONE, BOLD, NONE, THIN, NONE) => '┽',
	make_char_mask(DOTT, NONE, DOTT, NONE, BOLD, NONE, DOTT, NONE) => '┽',
	make_char_mask(THIN, NONE, DOTT, NONE, BOLD, NONE, DOTT, NONE) => '┽',
	make_char_mask(DOTT, NONE, THIN, NONE, BOLD, NONE, DOTT, NONE) => '┽',
	make_char_mask(DOTT, NONE, DOTT, NONE, BOLD, NONE, THIN, NONE) => '┽',
	make_char_mask(THIN, NONE, THIN, NONE, BOLD, NONE, DOTT, NONE) => '┽',
	make_char_mask(THIN, NONE, DOTT, NONE, BOLD, NONE, THIN, NONE) => '┽',
	make_char_mask(DOTT, NONE, THIN, NONE, BOLD, NONE, THIN, NONE) => '┽',
	make_char_mask(THIN, NONE, THIN, NONE, BDOT, NONE, THIN, NONE) => '┽',
	make_char_mask(DOTT, NONE, DOTT, NONE, BDOT, NONE, DOTT, NONE) => '┽',
	make_char_mask(THIN, NONE, DOTT, NONE, BDOT, NONE, DOTT, NONE) => '┽',
	make_char_mask(DOTT, NONE, THIN, NONE, BDOT, NONE, DOTT, NONE) => '┽',
	make_char_mask(DOTT, NONE, DOTT, NONE, BDOT, NONE, THIN, NONE) => '┽',
	make_char_mask(THIN, NONE, THIN, NONE, BDOT, NONE, DOTT, NONE) => '┽',
	make_char_mask(THIN, NONE, DOTT, NONE, BDOT, NONE, THIN, NONE) => '┽',
	make_char_mask(DOTT, NONE, THIN, NONE, BDOT, NONE, THIN, NONE) => '┽',
	make_char_mask(BOLD, NONE, THIN, NONE, THIN, NONE, THIN, NONE) => '┾',
	make_char_mask(BOLD, NONE, DOTT, NONE, DOTT, NONE, DOTT, NONE) => '┾',
	make_char_mask(BOLD, NONE, THIN, NONE, DOTT, NONE, DOTT, NONE) => '┾',
	make_char_mask(BOLD, NONE, DOTT, NONE, THIN, NONE, DOTT, NONE) => '┾',
	make_char_mask(BOLD, NONE, DOTT, NONE, DOTT, NONE, THIN, NONE) => '┾',
	make_char_mask(BOLD, NONE, THIN, NONE, THIN, NONE, DOTT, NONE) => '┾',
	make_char_mask(BOLD, NONE, THIN, NONE, DOTT, NONE, THIN, NONE) => '┾',
	make_char_mask(BOLD, NONE, DOTT, NONE, THIN, NONE, THIN, NONE) => '┾',
	make_char_mask(BDOT, NONE, THIN, NONE, THIN, NONE, THIN, NONE) => '┾',
	make_char_mask(BDOT, NONE, DOTT, NONE, DOTT, NONE, DOTT, NONE) => '┾',
	make_char_mask(BDOT, NONE, THIN, NONE, DOTT, NONE, DOTT, NONE) => '┾',
	make_char_mask(BDOT, NONE, DOTT, NONE, THIN, NONE, DOTT, NONE) => '┾',
	make_char_mask(BDOT, NONE, DOTT, NONE, DOTT, NONE, THIN, NONE) => '┾',
	make_char_mask(BDOT, NONE, THIN, NONE, THIN, NONE, DOTT, NONE) => '┾',
	make_char_mask(BDOT, NONE, THIN, NONE, DOTT, NONE, THIN, NONE) => '┾',
	make_char_mask(BDOT, NONE, DOTT, NONE, THIN, NONE, THIN, NONE) => '┾',
	make_char_mask(BOLD, NONE, THIN, NONE, BOLD, NONE, THIN, NONE) => '┿',
	make_char_mask(BDOT, NONE, THIN, NONE, BDOT, NONE, THIN, NONE) => '┿',
	make_char_mask(BOLD, NONE, THIN, NONE, BDOT, NONE, THIN, NONE) => '┿',
	make_char_mask(BDOT, NONE, THIN, NONE, BOLD, NONE, THIN, NONE) => '┿',
	make_char_mask(BOLD, NONE, DOTT, NONE, BOLD, NONE, DOTT, NONE) => '┿',
	make_char_mask(BDOT, NONE, DOTT, NONE, BDOT, NONE, DOTT, NONE) => '┿',
	make_char_mask(BOLD, NONE, DOTT, NONE, BDOT, NONE, DOTT, NONE) => '┿',
	make_char_mask(BDOT, NONE, DOTT, NONE, BOLD, NONE, DOTT, NONE) => '┿',
	make_char_mask(BOLD, NONE, THIN, NONE, BOLD, NONE, DOTT, NONE) => '┿',
	make_char_mask(BDOT, NONE, THIN, NONE, BDOT, NONE, DOTT, NONE) => '┿',
	make_char_mask(BOLD, NONE, THIN, NONE, BDOT, NONE, DOTT, NONE) => '┿',
	make_char_mask(BDOT, NONE, THIN, NONE, BOLD, NONE, DOTT, NONE) => '┿',
	make_char_mask(BOLD, NONE, DOTT, NONE, BOLD, NONE, THIN, NONE) => '┿',
	make_char_mask(BDOT, NONE, DOTT, NONE, BDOT, NONE, THIN, NONE) => '┿',
	make_char_mask(BOLD, NONE, DOTT, NONE, BDOT, NONE, THIN, NONE) => '┿',
	make_char_mask(BDOT, NONE, DOTT, NONE, BOLD, NONE, THIN, NONE) => '┿',
	make_char_mask(THIN, NONE, BOLD, NONE, THIN, NONE, THIN, NONE) => '╀',
	make_char_mask(DOTT, NONE, BOLD, NONE, DOTT, NONE, DOTT, NONE) => '╀',
	make_char_mask(THIN, NONE, BOLD, NONE, DOTT, NONE, DOTT, NONE) => '╀',
	make_char_mask(DOTT, NONE, BOLD, NONE, THIN, NONE, DOTT, NONE) => '╀',
	make_char_mask(DOTT, NONE, BOLD, NONE, DOTT, NONE, THIN, NONE) => '╀',
	make_char_mask(THIN, NONE, BOLD, NONE, THIN, NONE, DOTT, NONE) => '╀',
	make_char_mask(THIN, NONE, BOLD, NONE, DOTT, NONE, THIN, NONE) => '╀',
	make_char_mask(DOTT, NONE, BOLD, NONE, THIN, NONE, THIN, NONE) => '╀',
	make_char_mask(THIN, NONE, BDOT, NONE, THIN, NONE, THIN, NONE) => '╀',
	make_char_mask(DOTT, NONE, BDOT, NONE, DOTT, NONE, DOTT, NONE) => '╀',
	make_char_mask(THIN, NONE, BDOT, NONE, DOTT, NONE, DOTT, NONE) => '╀',
	make_char_mask(DOTT, NONE, BDOT, NONE, THIN, NONE, DOTT, NONE) => '╀',
	make_char_mask(DOTT, NONE, BDOT, NONE, DOTT, NONE, THIN, NONE) => '╀',
	make_char_mask(THIN, NONE, BDOT, NONE, THIN, NONE, DOTT, NONE) => '╀',
	make_char_mask(THIN, NONE, BDOT, NONE, DOTT, NONE, THIN, NONE) => '╀',
	make_char_mask(DOTT, NONE, BDOT, NONE, THIN, NONE, THIN, NONE) => '╀',
	make_char_mask(THIN, NONE, THIN, NONE, THIN, NONE, BOLD, NONE) => '╁',
	make_char_mask(DOTT, NONE, DOTT, NONE, DOTT, NONE, BOLD, NONE) => '╁',
	make_char_mask(THIN, NONE, DOTT, NONE, DOTT, NONE, BOLD, NONE) => '╁',
	make_char_mask(DOTT, NONE, THIN, NONE, DOTT, NONE, BOLD, NONE) => '╁',
	make_char_mask(DOTT, NONE, DOTT, NONE, THIN, NONE, BOLD, NONE) => '╁',
	make_char_mask(THIN, NONE, THIN, NONE, DOTT, NONE, BOLD, NONE) => '╁',
	make_char_mask(THIN, NONE, DOTT, NONE, THIN, NONE, BOLD, NONE) => '╁',
	make_char_mask(DOTT, NONE, THIN, NONE, THIN, NONE, BOLD, NONE) => '╁',
	make_char_mask(THIN, NONE, THIN, NONE, THIN, NONE, BDOT, NONE) => '╁',
	make_char_mask(DOTT, NONE, DOTT, NONE, DOTT, NONE, BDOT, NONE) => '╁',
	make_char_mask(THIN, NONE, DOTT, NONE, DOTT, NONE, BDOT, NONE) => '╁',
	make_char_mask(DOTT, NONE, THIN, NONE, DOTT, NONE, BDOT, NONE) => '╁',
	make_char_mask(DOTT, NONE, DOTT, NONE, THIN, NONE, BDOT, NONE) => '╁',
	make_char_mask(THIN, NONE, THIN, NONE, DOTT, NONE, BDOT, NONE) => '╁',
	make_char_mask(THIN, NONE, DOTT, NONE, THIN, NONE, BDOT, NONE) => '╁',
	make_char_mask(DOTT, NONE, THIN, NONE, THIN, NONE, BDOT, NONE) => '╁',
	make_char_mask(THIN, NONE, BOLD, NONE, THIN, NONE, BOLD, NONE) => '╂',
	make_char_mask(DOTT, NONE, BOLD, NONE, DOTT, NONE, BOLD, NONE) => '╂',
	make_char_mask(THIN, NONE, BOLD, NONE, DOTT, NONE, BOLD, NONE) => '╂',
	make_char_mask(DOTT, NONE, BOLD, NONE, THIN, NONE, BOLD, NONE) => '╂',
	make_char_mask(THIN, NONE, BDOT, NONE, THIN, NONE, BDOT, NONE) => '╂',
	make_char_mask(DOTT, NONE, BDOT, NONE, DOTT, NONE, BDOT, NONE) => '╂',
	make_char_mask(THIN, NONE, BDOT, NONE, DOTT, NONE, BDOT, NONE) => '╂',
	make_char_mask(DOTT, NONE, BDOT, NONE, THIN, NONE, BDOT, NONE) => '╂',
	make_char_mask(THIN, NONE, BOLD, NONE, THIN, NONE, BDOT, NONE) => '╂',
	make_char_mask(DOTT, NONE, BOLD, NONE, DOTT, NONE, BDOT, NONE) => '╂',
	make_char_mask(THIN, NONE, BOLD, NONE, DOTT, NONE, BDOT, NONE) => '╂',
	make_char_mask(DOTT, NONE, BOLD, NONE, THIN, NONE, BDOT, NONE) => '╂',
	make_char_mask(THIN, NONE, BDOT, NONE, THIN, NONE, BOLD, NONE) => '╂',
	make_char_mask(DOTT, NONE, BDOT, NONE, DOTT, NONE, BOLD, NONE) => '╂',
	make_char_mask(THIN, NONE, BDOT, NONE, DOTT, NONE, BOLD, NONE) => '╂',
	make_char_mask(DOTT, NONE, BDOT, NONE, THIN, NONE, BOLD, NONE) => '╂',
	make_char_mask(THIN, NONE, BOLD, NONE, BOLD, NONE, THIN, NONE) => '╃',
	make_char_mask(DOTT, NONE, BOLD, NONE, BOLD, NONE, DOTT, NONE) => '╃',
	make_char_mask(THIN, NONE, BOLD, NONE, BOLD, NONE, DOTT, NONE) => '╃',
	make_char_mask(DOTT, NONE, BOLD, NONE, BOLD, NONE, THIN, NONE) => '╃',
	make_char_mask(THIN, NONE, BDOT, NONE, BDOT, NONE, THIN, NONE) => '╃',
	make_char_mask(DOTT, NONE, BDOT, NONE, BDOT, NONE, DOTT, NONE) => '╃',
	make_char_mask(THIN, NONE, BDOT, NONE, BDOT, NONE, DOTT, NONE) => '╃',
	make_char_mask(DOTT, NONE, BDOT, NONE, BDOT, NONE, THIN, NONE) => '╃',
	make_char_mask(THIN, NONE, BDOT, NONE, BOLD, NONE, THIN, NONE) => '╃',
	make_char_mask(DOTT, NONE, BDOT, NONE, BOLD, NONE, DOTT, NONE) => '╃',
	make_char_mask(THIN, NONE, BDOT, NONE, BOLD, NONE, DOTT, NONE) => '╃',
	make_char_mask(DOTT, NONE, BDOT, NONE, BOLD, NONE, THIN, NONE) => '╃',
	make_char_mask(THIN, NONE, BOLD, NONE, BDOT, NONE, THIN, NONE) => '╃',
	make_char_mask(DOTT, NONE, BOLD, NONE, BDOT, NONE, DOTT, NONE) => '╃',
	make_char_mask(THIN, NONE, BOLD, NONE, BDOT, NONE, DOTT, NONE) => '╃',
	make_char_mask(DOTT, NONE, BOLD, NONE, BDOT, NONE, THIN, NONE) => '╃',
	make_char_mask(BOLD, NONE, BOLD, NONE, THIN, NONE, THIN, NONE) => '╄',
	make_char_mask(BOLD, NONE, BOLD, NONE, DOTT, NONE, DOTT, NONE) => '╄',
	make_char_mask(BOLD, NONE, BOLD, NONE, THIN, NONE, DOTT, NONE) => '╄',
	make_char_mask(BOLD, NONE, BOLD, NONE, DOTT, NONE, THIN, NONE) => '╄',
	make_char_mask(BDOT, NONE, BDOT, NONE, THIN, NONE, THIN, NONE) => '╄',
	make_char_mask(BDOT, NONE, BDOT, NONE, DOTT, NONE, DOTT, NONE) => '╄',
	make_char_mask(BDOT, NONE, BDOT, NONE, THIN, NONE, DOTT, NONE) => '╄',
	make_char_mask(BDOT, NONE, BDOT, NONE, DOTT, NONE, THIN, NONE) => '╄',
	make_char_mask(BOLD, NONE, BDOT, NONE, THIN, NONE, THIN, NONE) => '╄',
	make_char_mask(BOLD, NONE, BDOT, NONE, DOTT, NONE, DOTT, NONE) => '╄',
	make_char_mask(BOLD, NONE, BDOT, NONE, THIN, NONE, DOTT, NONE) => '╄',
	make_char_mask(BOLD, NONE, BDOT, NONE, DOTT, NONE, THIN, NONE) => '╄',
	make_char_mask(BDOT, NONE, BOLD, NONE, THIN, NONE, THIN, NONE) => '╄',
	make_char_mask(BDOT, NONE, BOLD, NONE, DOTT, NONE, DOTT, NONE) => '╄',
	make_char_mask(BDOT, NONE, BOLD, NONE, THIN, NONE, DOTT, NONE) => '╄',
	make_char_mask(BDOT, NONE, BOLD, NONE, DOTT, NONE, THIN, NONE) => '╄',
	make_char_mask(THIN, NONE, THIN, NONE, BOLD, NONE, BOLD, NONE) => '╅',
	make_char_mask(DOTT, NONE, DOTT, NONE, BOLD, NONE, BOLD, NONE) => '╅',
	make_char_mask(THIN, NONE, DOTT, NONE, BOLD, NONE, BOLD, NONE) => '╅',
	make_char_mask(DOTT, NONE, THIN, NONE, BOLD, NONE, BOLD, NONE) => '╅',
	make_char_mask(THIN, NONE, THIN, NONE, BDOT, NONE, BDOT, NONE) => '╅',
	make_char_mask(DOTT, NONE, DOTT, NONE, BDOT, NONE, BDOT, NONE) => '╅',
	make_char_mask(THIN, NONE, DOTT, NONE, BDOT, NONE, BDOT, NONE) => '╅',
	make_char_mask(DOTT, NONE, THIN, NONE, BDOT, NONE, BDOT, NONE) => '╅',
	make_char_mask(THIN, NONE, THIN, NONE, BOLD, NONE, BDOT, NONE) => '╅',
	make_char_mask(DOTT, NONE, DOTT, NONE, BOLD, NONE, BDOT, NONE) => '╅',
	make_char_mask(THIN, NONE, DOTT, NONE, BOLD, NONE, BDOT, NONE) => '╅',
	make_char_mask(DOTT, NONE, THIN, NONE, BOLD, NONE, BDOT, NONE) => '╅',
	make_char_mask(THIN, NONE, THIN, NONE, BDOT, NONE, BOLD, NONE) => '╅',
	make_char_mask(DOTT, NONE, DOTT, NONE, BDOT, NONE, BOLD, NONE) => '╅',
	make_char_mask(THIN, NONE, DOTT, NONE, BDOT, NONE, BOLD, NONE) => '╅',
	make_char_mask(DOTT, NONE, THIN, NONE, BDOT, NONE, BOLD, NONE) => '╅',
	make_char_mask(BOLD, NONE, THIN, NONE, THIN, NONE, BOLD, NONE) => '╆',
	make_char_mask(BOLD, NONE, DOTT, NONE, DOTT, NONE, BOLD, NONE) => '╆',
	make_char_mask(BOLD, NONE, THIN, NONE, DOTT, NONE, BOLD, NONE) => '╆',
	make_char_mask(BOLD, NONE, DOTT, NONE, THIN, NONE, BOLD, NONE) => '╆',
	make_char_mask(BDOT, NONE, THIN, NONE, THIN, NONE, BDOT, NONE) => '╆',
	make_char_mask(BDOT, NONE, DOTT, NONE, DOTT, NONE, BDOT, NONE) => '╆',
	make_char_mask(BDOT, NONE, THIN, NONE, DOTT, NONE, BDOT, NONE) => '╆',
	make_char_mask(BDOT, NONE, DOTT, NONE, THIN, NONE, BDOT, NONE) => '╆',
	make_char_mask(BOLD, NONE, THIN, NONE, THIN, NONE, BDOT, NONE) => '╆',
	make_char_mask(BOLD, NONE, DOTT, NONE, DOTT, NONE, BDOT, NONE) => '╆',
	make_char_mask(BOLD, NONE, THIN, NONE, DOTT, NONE, BDOT, NONE) => '╆',
	make_char_mask(BOLD, NONE, DOTT, NONE, THIN, NONE, BDOT, NONE) => '╆',
	make_char_mask(BDOT, NONE, THIN, NONE, THIN, NONE, BOLD, NONE) => '╆',
	make_char_mask(BDOT, NONE, DOTT, NONE, DOTT, NONE, BOLD, NONE) => '╆',
	make_char_mask(BDOT, NONE, THIN, NONE, DOTT, NONE, BOLD, NONE) => '╆',
	make_char_mask(BDOT, NONE, DOTT, NONE, THIN, NONE, BOLD, NONE) => '╆',
	make_char_mask(BOLD, NONE, BOLD, NONE, BOLD, NONE, THIN, NONE) => '╇',
	make_char_mask(BDOT, NONE, BDOT, NONE, BDOT, NONE, THIN, NONE) => '╇',
	make_char_mask(BOLD, NONE, BDOT, NONE, BDOT, NONE, THIN, NONE) => '╇',
	make_char_mask(BDOT, NONE, BOLD, NONE, BDOT, NONE, THIN, NONE) => '╇',
	make_char_mask(BDOT, NONE, BDOT, NONE, BOLD, NONE, THIN, NONE) => '╇',
	make_char_mask(BOLD, NONE, BOLD, NONE, BDOT, NONE, THIN, NONE) => '╇',
	make_char_mask(BOLD, NONE, BDOT, NONE, BOLD, NONE, THIN, NONE) => '╇',
	make_char_mask(BDOT, NONE, BOLD, NONE, BOLD, NONE, THIN, NONE) => '╇',
	make_char_mask(BOLD, NONE, BOLD, NONE, BOLD, NONE, DOTT, NONE) => '╇',
	make_char_mask(BDOT, NONE, BDOT, NONE, BDOT, NONE, DOTT, NONE) => '╇',
	make_char_mask(BOLD, NONE, BDOT, NONE, BDOT, NONE, DOTT, NONE) => '╇',
	make_char_mask(BDOT, NONE, BOLD, NONE, BDOT, NONE, DOTT, NONE) => '╇',
	make_char_mask(BDOT, NONE, BDOT, NONE, BOLD, NONE, DOTT, NONE) => '╇',
	make_char_mask(BOLD, NONE, BOLD, NONE, BDOT, NONE, DOTT, NONE) => '╇',
	make_char_mask(BOLD, NONE, BDOT, NONE, BOLD, NONE, DOTT, NONE) => '╇',
	make_char_mask(BDOT, NONE, BOLD, NONE, BOLD, NONE, DOTT, NONE) => '╇',
	make_char_mask(BOLD, NONE, THIN, NONE, BOLD, NONE, BOLD, NONE) => '╈',
	make_char_mask(BDOT, NONE, THIN, NONE, BDOT, NONE, BDOT, NONE) => '╈',
	make_char_mask(BOLD, NONE, THIN, NONE, BDOT, NONE, BDOT, NONE) => '╈',
	make_char_mask(BDOT, NONE, THIN, NONE, BOLD, NONE, BDOT, NONE) => '╈',
	make_char_mask(BDOT, NONE, THIN, NONE, BDOT, NONE, BOLD, NONE) => '╈',
	make_char_mask(BOLD, NONE, THIN, NONE, BOLD, NONE, BDOT, NONE) => '╈',
	make_char_mask(BOLD, NONE, THIN, NONE, BDOT, NONE, BOLD, NONE) => '╈',
	make_char_mask(BDOT, NONE, THIN, NONE, BOLD, NONE, BOLD, NONE) => '╈',
	make_char_mask(BOLD, NONE, DOTT, NONE, BOLD, NONE, BOLD, NONE) => '╈',
	make_char_mask(BDOT, NONE, DOTT, NONE, BDOT, NONE, BDOT, NONE) => '╈',
	make_char_mask(BOLD, NONE, DOTT, NONE, BDOT, NONE, BDOT, NONE) => '╈',
	make_char_mask(BDOT, NONE, DOTT, NONE, BOLD, NONE, BDOT, NONE) => '╈',
	make_char_mask(BDOT, NONE, DOTT, NONE, BDOT, NONE, BOLD, NONE) => '╈',
	make_char_mask(BOLD, NONE, DOTT, NONE, BOLD, NONE, BDOT, NONE) => '╈',
	make_char_mask(BOLD, NONE, DOTT, NONE, BDOT, NONE, BOLD, NONE) => '╈',
	make_char_mask(BDOT, NONE, DOTT, NONE, BOLD, NONE, BOLD, NONE) => '╈',
	make_char_mask(THIN, NONE, BOLD, NONE, BOLD, NONE, BOLD, NONE) => '╉',
	make_char_mask(THIN, NONE, BDOT, NONE, BDOT, NONE, BDOT, NONE) => '╉',
	make_char_mask(THIN, NONE, BOLD, NONE, BDOT, NONE, BDOT, NONE) => '╉',
	make_char_mask(THIN, NONE, BDOT, NONE, BOLD, NONE, BDOT, NONE) => '╉',
	make_char_mask(THIN, NONE, BDOT, NONE, BDOT, NONE, BOLD, NONE) => '╉',
	make_char_mask(THIN, NONE, BDOT, NONE, BOLD, NONE, BOLD, NONE) => '╉',
	make_char_mask(THIN, NONE, BOLD, NONE, BDOT, NONE, BOLD, NONE) => '╉',
	make_char_mask(THIN, NONE, BOLD, NONE, BOLD, NONE, BDOT, NONE) => '╉',
	make_char_mask(DOTT, NONE, BOLD, NONE, BOLD, NONE, BOLD, NONE) => '╉',
	make_char_mask(DOTT, NONE, BDOT, NONE, BDOT, NONE, BDOT, NONE) => '╉',
	make_char_mask(DOTT, NONE, BOLD, NONE, BDOT, NONE, BDOT, NONE) => '╉',
	make_char_mask(DOTT, NONE, BDOT, NONE, BOLD, NONE, BDOT, NONE) => '╉',
	make_char_mask(DOTT, NONE, BDOT, NONE, BDOT, NONE, BOLD, NONE) => '╉',
	make_char_mask(DOTT, NONE, BDOT, NONE, BOLD, NONE, BOLD, NONE) => '╉',
	make_char_mask(DOTT, NONE, BOLD, NONE, BDOT, NONE, BOLD, NONE) => '╉',
	make_char_mask(DOTT, NONE, BOLD, NONE, BOLD, NONE, BDOT, NONE) => '╉',
	make_char_mask(BOLD, NONE, BOLD, NONE, THIN, NONE, BOLD, NONE) => '╊',
	make_char_mask(BDOT, NONE, BDOT, NONE, THIN, NONE, BDOT, NONE) => '╊',
	make_char_mask(BOLD, NONE, BDOT, NONE, THIN, NONE, BDOT, NONE) => '╊',
	make_char_mask(BDOT, NONE, BOLD, NONE, THIN, NONE, BDOT, NONE) => '╊',
	make_char_mask(BDOT, NONE, BDOT, NONE, THIN, NONE, BOLD, NONE) => '╊',
	make_char_mask(BDOT, NONE, BOLD, NONE, THIN, NONE, BOLD, NONE) => '╊',
	make_char_mask(BOLD, NONE, BDOT, NONE, THIN, NONE, BOLD, NONE) => '╊',
	make_char_mask(BOLD, NONE, BOLD, NONE, THIN, NONE, BDOT, NONE) => '╊',
	make_char_mask(BOLD, NONE, BOLD, NONE, DOTT, NONE, BOLD, NONE) => '╊',
	make_char_mask(BDOT, NONE, BDOT, NONE, DOTT, NONE, BDOT, NONE) => '╊',
	make_char_mask(BOLD, NONE, BDOT, NONE, DOTT, NONE, BDOT, NONE) => '╊',
	make_char_mask(BDOT, NONE, BOLD, NONE, DOTT, NONE, BDOT, NONE) => '╊',
	make_char_mask(BDOT, NONE, BDOT, NONE, DOTT, NONE, BOLD, NONE) => '╊',
	make_char_mask(BDOT, NONE, BOLD, NONE, DOTT, NONE, BOLD, NONE) => '╊',
	make_char_mask(BOLD, NONE, BDOT, NONE, DOTT, NONE, BOLD, NONE) => '╊',
	make_char_mask(BOLD, NONE, BOLD, NONE, DOTT, NONE, BDOT, NONE) => '╊',
	make_char_mask(THIN, NONE, DOBL, NONE, THIN, NONE, DOBL, NONE) => '╫',
	make_char_mask(DOTT, NONE, DOBL, NONE, DOTT, NONE, DOBL, NONE) => '╫',
	make_char_mask(THIN, NONE, DOBL, NONE, DOTT, NONE, DOBL, NONE) => '╫',
	make_char_mask(DOTT, NONE, DOBL, NONE, THIN, NONE, DOBL, NONE) => '╫',
	make_char_mask(DOBL, NONE, THIN, NONE, DOBL, NONE, THIN, NONE) => '╪',
	make_char_mask(DOBL, NONE, DOTT, NONE, DOBL, NONE, DOTT, NONE) => '╪',
	make_char_mask(DOBL, NONE, THIN, NONE, DOBL, NONE, DOTT, NONE) => '╪',
	make_char_mask(DOBL, NONE, DOTT, NONE, DOBL, NONE, THIN, NONE) => '╪',
	make_char_mask(THIN, NONE, THIN, NONE, THIN, NONE, THIN, NONE) => '┼',
	make_char_mask(DOTT, NONE, DOTT, NONE, DOTT, NONE, DOTT, NONE) => '┼',
	make_char_mask(THIN, NONE, DOTT, NONE, DOTT, NONE, DOTT, NONE) => '┼',
	make_char_mask(DOTT, NONE, THIN, NONE, DOTT, NONE, DOTT, NONE) => '┼',
	make_char_mask(DOTT, NONE, DOTT, NONE, THIN, NONE, DOTT, NONE) => '┼',
	make_char_mask(DOTT, NONE, DOTT, NONE, DOTT, NONE, THIN, NONE) => '┼',
	make_char_mask(THIN, NONE, THIN, NONE, DOTT, NONE, DOTT, NONE) => '┼',
	make_char_mask(THIN, NONE, DOTT, NONE, THIN, NONE, DOTT, NONE) => '┼',
	make_char_mask(THIN, NONE, DOTT, NONE, DOTT, NONE, THIN, NONE) => '┼',
	make_char_mask(DOTT, NONE, THIN, NONE, THIN, NONE, DOTT, NONE) => '┼',
	make_char_mask(DOTT, NONE, THIN, NONE, DOTT, NONE, THIN, NONE) => '┼',
	make_char_mask(DOTT, NONE, DOTT, NONE, THIN, NONE, THIN, NONE) => '┼',
	make_char_mask(THIN, NONE, THIN, NONE, THIN, NONE, DOTT, NONE) => '┼',
	make_char_mask(THIN, NONE, THIN, NONE, DOTT, NONE, THIN, NONE) => '┼',
	make_char_mask(THIN, NONE, DOTT, NONE, THIN, NONE, THIN, NONE) => '┼',
	make_char_mask(DOTT, NONE, THIN, NONE, THIN, NONE, THIN, NONE) => '┼',
	make_char_mask(BOLD, NONE, BOLD, NONE, BOLD, NONE, BOLD, NONE) => '╋',
	make_char_mask(BDOT, NONE, BDOT, NONE, BDOT, NONE, BDOT, NONE) => '╋',
	make_char_mask(BOLD, NONE, BDOT, NONE, BDOT, NONE, BDOT, NONE) => '╋',
	make_char_mask(BDOT, NONE, BOLD, NONE, BDOT, NONE, BDOT, NONE) => '╋',
	make_char_mask(BDOT, NONE, BDOT, NONE, BOLD, NONE, BDOT, NONE) => '╋',
	make_char_mask(BDOT, NONE, BDOT, NONE, BDOT, NONE, BOLD, NONE) => '╋',
	make_char_mask(BOLD, NONE, BOLD, NONE, BDOT, NONE, BDOT, NONE) => '╋',
	make_char_mask(BOLD, NONE, BDOT, NONE, BOLD, NONE, BDOT, NONE) => '╋',
	make_char_mask(BOLD, NONE, BDOT, NONE, BDOT, NONE, BOLD, NONE) => '╋',
	make_char_mask(BDOT, NONE, BOLD, NONE, BOLD, NONE, BDOT, NONE) => '╋',
	make_char_mask(BDOT, NONE, BOLD, NONE, BDOT, NONE, BOLD, NONE) => '╋',
	make_char_mask(BDOT, NONE, BDOT, NONE, BOLD, NONE, BOLD, NONE) => '╋',
	make_char_mask(BDOT, NONE, BOLD, NONE, BOLD, NONE, BOLD, NONE) => '╋',
	make_char_mask(BOLD, NONE, BDOT, NONE, BOLD, NONE, BOLD, NONE) => '╋',
	make_char_mask(BOLD, NONE, BOLD, NONE, BDOT, NONE, BOLD, NONE) => '╋',
	make_char_mask(BOLD, NONE, BOLD, NONE, BOLD, NONE, BDOT, NONE) => '╋',
	make_char_mask(DOBL, NONE, DOBL, NONE, DOBL, NONE, DOBL, NONE) => '╬',
	make_char_mask(THIN, NONE, THIN, NONE, BOLD, NONE, NONE, NONE) => '┵',
	make_char_mask(DOTT, NONE, DOTT, NONE, BOLD, NONE, NONE, NONE) => '┵',
	make_char_mask(THIN, NONE, DOTT, NONE, BOLD, NONE, NONE, NONE) => '┵',
	make_char_mask(DOTT, NONE, THIN, NONE, BOLD, NONE, NONE, NONE) => '┵',
	make_char_mask(THIN, NONE, THIN, NONE, BDOT, NONE, NONE, NONE) => '┵',
	make_char_mask(DOTT, NONE, DOTT, NONE, BDOT, NONE, NONE, NONE) => '┵',
	make_char_mask(THIN, NONE, DOTT, NONE, BDOT, NONE, NONE, NONE) => '┵',
	make_char_mask(DOTT, NONE, THIN, NONE, BDOT, NONE, NONE, NONE) => '┵',
	make_char_mask(BOLD, NONE, THIN, NONE, THIN, NONE, NONE, NONE) => '┶',
	make_char_mask(BOLD, NONE, DOTT, NONE, DOTT, NONE, NONE, NONE) => '┶',
	make_char_mask(BOLD, NONE, THIN, NONE, DOTT, NONE, NONE, NONE) => '┶',
	make_char_mask(BOLD, NONE, DOTT, NONE, THIN, NONE, NONE, NONE) => '┶',
	make_char_mask(BDOT, NONE, THIN, NONE, THIN, NONE, NONE, NONE) => '┶',
	make_char_mask(BDOT, NONE, DOTT, NONE, DOTT, NONE, NONE, NONE) => '┶',
	make_char_mask(BDOT, NONE, THIN, NONE, DOTT, NONE, NONE, NONE) => '┶',
	make_char_mask(BDOT, NONE, DOTT, NONE, THIN, NONE, NONE, NONE) => '┶',
	make_char_mask(BOLD, NONE, THIN, NONE, BOLD, NONE, NONE, NONE) => '┷',
	make_char_mask(BDOT, NONE, THIN, NONE, BDOT, NONE, NONE, NONE) => '┷',
	make_char_mask(BOLD, NONE, THIN, NONE, BDOT, NONE, NONE, NONE) => '┷',
	make_char_mask(BDOT, NONE, THIN, NONE, BOLD, NONE, NONE, NONE) => '┷',
	make_char_mask(BOLD, NONE, DOTT, NONE, BOLD, NONE, NONE, NONE) => '┷',
	make_char_mask(BDOT, NONE, DOTT, NONE, BDOT, NONE, NONE, NONE) => '┷',
	make_char_mask(BOLD, NONE, DOTT, NONE, BDOT, NONE, NONE, NONE) => '┷',
	make_char_mask(BDOT, NONE, DOTT, NONE, BOLD, NONE, NONE, NONE) => '┷',
	make_char_mask(THIN, NONE, BOLD, NONE, THIN, NONE, NONE, NONE) => '┸',
	make_char_mask(DOTT, NONE, BOLD, NONE, DOTT, NONE, NONE, NONE) => '┸',
	make_char_mask(THIN, NONE, BOLD, NONE, DOTT, NONE, NONE, NONE) => '┸',
	make_char_mask(DOTT, NONE, BOLD, NONE, THIN, NONE, NONE, NONE) => '┸',
	make_char_mask(THIN, NONE, BDOT, NONE, THIN, NONE, NONE, NONE) => '┸',
	make_char_mask(DOTT, NONE, BDOT, NONE, DOTT, NONE, NONE, NONE) => '┸',
	make_char_mask(THIN, NONE, BDOT, NONE, DOTT, NONE, NONE, NONE) => '┸',
	make_char_mask(DOTT, NONE, BDOT, NONE, THIN, NONE, NONE, NONE) => '┸',
	make_char_mask(THIN, NONE, BOLD, NONE, BOLD, NONE, NONE, NONE) => '┹',
	make_char_mask(THIN, NONE, BDOT, NONE, BDOT, NONE, NONE, NONE) => '┹',
	make_char_mask(THIN, NONE, BOLD, NONE, BDOT, NONE, NONE, NONE) => '┹',
	make_char_mask(THIN, NONE, BDOT, NONE, BOLD, NONE, NONE, NONE) => '┹',
	make_char_mask(DOTT, NONE, BOLD, NONE, BOLD, NONE, NONE, NONE) => '┹',
	make_char_mask(DOTT, NONE, BDOT, NONE, BDOT, NONE, NONE, NONE) => '┹',
	make_char_mask(DOTT, NONE, BOLD, NONE, BDOT, NONE, NONE, NONE) => '┹',
	make_char_mask(DOTT, NONE, BDOT, NONE, BOLD, NONE, NONE, NONE) => '┹',
	make_char_mask(BOLD, NONE, BOLD, NONE, THIN, NONE, NONE, NONE) => '┺',
	make_char_mask(BDOT, NONE, BDOT, NONE, THIN, NONE, NONE, NONE) => '┺',
	make_char_mask(BOLD, NONE, BDOT, NONE, THIN, NONE, NONE, NONE) => '┺',
	make_char_mask(BDOT, NONE, BOLD, NONE, THIN, NONE, NONE, NONE) => '┺',
	make_char_mask(BOLD, NONE, BOLD, NONE, DOTT, NONE, NONE, NONE) => '┺',
	make_char_mask(BDOT, NONE, BDOT, NONE, DOTT, NONE, NONE, NONE) => '┺',
	make_char_mask(BOLD, NONE, BDOT, NONE, DOTT, NONE, NONE, NONE) => '┺',
	make_char_mask(BDOT, NONE, BOLD, NONE, DOTT, NONE, NONE, NONE) => '┺',
	make_char_mask(THIN, NONE, NONE, NONE, BOLD, NONE, THIN, NONE) => '┭',
	make_char_mask(DOTT, NONE, NONE, NONE, BOLD, NONE, DOTT, NONE) => '┭',
	make_char_mask(THIN, NONE, NONE, NONE, BOLD, NONE, DOTT, NONE) => '┭',
	make_char_mask(DOTT, NONE, NONE, NONE, BOLD, NONE, THIN, NONE) => '┭',
	make_char_mask(THIN, NONE, NONE, NONE, BDOT, NONE, THIN, NONE) => '┭',
	make_char_mask(DOTT, NONE, NONE, NONE, BDOT, NONE, DOTT, NONE) => '┭',
	make_char_mask(THIN, NONE, NONE, NONE, BDOT, NONE, DOTT, NONE) => '┭',
	make_char_mask(DOTT, NONE, NONE, NONE, BDOT, NONE, THIN, NONE) => '┭',
	make_char_mask(BOLD, NONE, NONE, NONE, THIN, NONE, THIN, NONE) => '┮',
	make_char_mask(BOLD, NONE, NONE, NONE, DOTT, NONE, DOTT, NONE) => '┮',
	make_char_mask(BOLD, NONE, NONE, NONE, THIN, NONE, DOTT, NONE) => '┮',
	make_char_mask(BOLD, NONE, NONE, NONE, DOTT, NONE, THIN, NONE) => '┮',
	make_char_mask(BDOT, NONE, NONE, NONE, THIN, NONE, THIN, NONE) => '┮',
	make_char_mask(BDOT, NONE, NONE, NONE, DOTT, NONE, DOTT, NONE) => '┮',
	make_char_mask(BDOT, NONE, NONE, NONE, THIN, NONE, DOTT, NONE) => '┮',
	make_char_mask(BDOT, NONE, NONE, NONE, DOTT, NONE, THIN, NONE) => '┮',
	make_char_mask(BOLD, NONE, NONE, NONE, BOLD, NONE, THIN, NONE) => '┯',
	make_char_mask(BDOT, NONE, NONE, NONE, BDOT, NONE, THIN, NONE) => '┯',
	make_char_mask(BOLD, NONE, NONE, NONE, BDOT, NONE, THIN, NONE) => '┯',
	make_char_mask(BDOT, NONE, NONE, NONE, BOLD, NONE, THIN, NONE) => '┯',
	make_char_mask(BOLD, NONE, NONE, NONE, BOLD, NONE, DOTT, NONE) => '┯',
	make_char_mask(BDOT, NONE, NONE, NONE, BDOT, NONE, DOTT, NONE) => '┯',
	make_char_mask(BOLD, NONE, NONE, NONE, BDOT, NONE, DOTT, NONE) => '┯',
	make_char_mask(BDOT, NONE, NONE, NONE, BOLD, NONE, DOTT, NONE) => '┯',
	make_char_mask(THIN, NONE, NONE, NONE, THIN, NONE, BOLD, NONE) => '┰',
	make_char_mask(DOTT, NONE, NONE, NONE, DOTT, NONE, BOLD, NONE) => '┰',
	make_char_mask(THIN, NONE, NONE, NONE, DOTT, NONE, BOLD, NONE) => '┰',
	make_char_mask(DOTT, NONE, NONE, NONE, THIN, NONE, BOLD, NONE) => '┰',
	make_char_mask(THIN, NONE, NONE, NONE, THIN, NONE, BDOT, NONE) => '┰',
	make_char_mask(DOTT, NONE, NONE, NONE, DOTT, NONE, BDOT, NONE) => '┰',
	make_char_mask(THIN, NONE, NONE, NONE, DOTT, NONE, BDOT, NONE) => '┰',
	make_char_mask(DOTT, NONE, NONE, NONE, THIN, NONE, BDOT, NONE) => '┰',
	make_char_mask(THIN, NONE, NONE, NONE, BOLD, NONE, BOLD, NONE) => '┱',
	make_char_mask(THIN, NONE, NONE, NONE, BDOT, NONE, BDOT, NONE) => '┱',
	make_char_mask(THIN, NONE, NONE, NONE, BOLD, NONE, BDOT, NONE) => '┱',
	make_char_mask(THIN, NONE, NONE, NONE, BDOT, NONE, BOLD, NONE) => '┱',
	make_char_mask(DOTT, NONE, NONE, NONE, BOLD, NONE, BOLD, NONE) => '┱',
	make_char_mask(DOTT, NONE, NONE, NONE, BDOT, NONE, BDOT, NONE) => '┱',
	make_char_mask(DOTT, NONE, NONE, NONE, BOLD, NONE, BDOT, NONE) => '┱',
	make_char_mask(DOTT, NONE, NONE, NONE, BDOT, NONE, BOLD, NONE) => '┱',
	make_char_mask(BOLD, NONE, NONE, NONE, THIN, NONE, BOLD, NONE) => '┲',
	make_char_mask(BDOT, NONE, NONE, NONE, THIN, NONE, BDOT, NONE) => '┲',
	make_char_mask(BDOT, NONE, NONE, NONE, THIN, NONE, BOLD, NONE) => '┲',
	make_char_mask(BOLD, NONE, NONE, NONE, THIN, NONE, BDOT, NONE) => '┲',
	make_char_mask(BOLD, NONE, NONE, NONE, DOTT, NONE, BOLD, NONE) => '┲',
	make_char_mask(BDOT, NONE, NONE, NONE, DOTT, NONE, BDOT, NONE) => '┲',
	make_char_mask(BDOT, NONE, NONE, NONE, DOTT, NONE, BOLD, NONE) => '┲',
	make_char_mask(BOLD, NONE, NONE, NONE, DOTT, NONE, BDOT, NONE) => '┲',
	make_char_mask(NONE, NONE, THIN, NONE, BOLD, NONE, THIN, NONE) => '┥',
	make_char_mask(NONE, NONE, DOTT, NONE, BOLD, NONE, DOTT, NONE) => '┥',
	make_char_mask(NONE, NONE, DOTT, NONE, BOLD, NONE, THIN, NONE) => '┥',
	make_char_mask(NONE, NONE, THIN, NONE, BOLD, NONE, DOTT, NONE) => '┥',
	make_char_mask(NONE, NONE, THIN, NONE, BDOT, NONE, THIN, NONE) => '┥',
	make_char_mask(NONE, NONE, DOTT, NONE, BDOT, NONE, DOTT, NONE) => '┥',
	make_char_mask(NONE, NONE, DOTT, NONE, BDOT, NONE, THIN, NONE) => '┥',
	make_char_mask(NONE, NONE, THIN, NONE, BDOT, NONE, DOTT, NONE) => '┥',
	make_char_mask(NONE, NONE, BOLD, NONE, THIN, NONE, THIN, NONE) => '┦',
	make_char_mask(NONE, NONE, BOLD, NONE, DOTT, NONE, DOTT, NONE) => '┦',
	make_char_mask(NONE, NONE, BOLD, NONE, DOTT, NONE, THIN, NONE) => '┦',
	make_char_mask(NONE, NONE, BOLD, NONE, THIN, NONE, DOTT, NONE) => '┦',
	make_char_mask(NONE, NONE, BDOT, NONE, THIN, NONE, THIN, NONE) => '┦',
	make_char_mask(NONE, NONE, BDOT, NONE, DOTT, NONE, DOTT, NONE) => '┦',
	make_char_mask(NONE, NONE, BDOT, NONE, DOTT, NONE, THIN, NONE) => '┦',
	make_char_mask(NONE, NONE, BDOT, NONE, THIN, NONE, DOTT, NONE) => '┦',
	make_char_mask(NONE, NONE, THIN, NONE, THIN, NONE, BOLD, NONE) => '┧',
	make_char_mask(NONE, NONE, DOTT, NONE, DOTT, NONE, BOLD, NONE) => '┧',
	make_char_mask(NONE, NONE, THIN, NONE, DOTT, NONE, BOLD, NONE) => '┧',
	make_char_mask(NONE, NONE, DOTT, NONE, THIN, NONE, BOLD, NONE) => '┧',
	make_char_mask(NONE, NONE, THIN, NONE, THIN, NONE, BDOT, NONE) => '┧',
	make_char_mask(NONE, NONE, DOTT, NONE, DOTT, NONE, BDOT, NONE) => '┧',
	make_char_mask(NONE, NONE, THIN, NONE, DOTT, NONE, BDOT, NONE) => '┧',
	make_char_mask(NONE, NONE, DOTT, NONE, THIN, NONE, BDOT, NONE) => '┧',
	make_char_mask(NONE, NONE, BOLD, NONE, THIN, NONE, BOLD, NONE) => '┨',
	make_char_mask(NONE, NONE, BDOT, NONE, THIN, NONE, BDOT, NONE) => '┨',
	make_char_mask(NONE, NONE, BDOT, NONE, THIN, NONE, BOLD, NONE) => '┨',
	make_char_mask(NONE, NONE, BOLD, NONE, THIN, NONE, BDOT, NONE) => '┨',
	make_char_mask(NONE, NONE, BOLD, NONE, DOTT, NONE, BOLD, NONE) => '┨',
	make_char_mask(NONE, NONE, BDOT, NONE, DOTT, NONE, BDOT, NONE) => '┨',
	make_char_mask(NONE, NONE, BDOT, NONE, DOTT, NONE, BOLD, NONE) => '┨',
	make_char_mask(NONE, NONE, BOLD, NONE, DOTT, NONE, BDOT, NONE) => '┨',
	make_char_mask(NONE, NONE, BOLD, NONE, BOLD, NONE, THIN, NONE) => '┩',
	make_char_mask(NONE, NONE, BDOT, NONE, BDOT, NONE, THIN, NONE) => '┩',
	make_char_mask(NONE, NONE, BOLD, NONE, BDOT, NONE, THIN, NONE) => '┩',
	make_char_mask(NONE, NONE, BDOT, NONE, BOLD, NONE, THIN, NONE) => '┩',
	make_char_mask(NONE, NONE, BOLD, NONE, BOLD, NONE, DOTT, NONE) => '┩',
	make_char_mask(NONE, NONE, BDOT, NONE, BDOT, NONE, DOTT, NONE) => '┩',
	make_char_mask(NONE, NONE, BOLD, NONE, BDOT, NONE, DOTT, NONE) => '┩',
	make_char_mask(NONE, NONE, BDOT, NONE, BOLD, NONE, DOTT, NONE) => '┩',
	make_char_mask(NONE, NONE, THIN, NONE, BOLD, NONE, BOLD, NONE) => '┪',
	make_char_mask(NONE, NONE, THIN, NONE, BDOT, NONE, BDOT, NONE) => '┪',
	make_char_mask(NONE, NONE, THIN, NONE, BOLD, NONE, BDOT, NONE) => '┪',
	make_char_mask(NONE, NONE, THIN, NONE, BDOT, NONE, BOLD, NONE) => '┪',
	make_char_mask(NONE, NONE, DOTT, NONE, BOLD, NONE, BOLD, NONE) => '┪',
	make_char_mask(NONE, NONE, DOTT, NONE, BDOT, NONE, BDOT, NONE) => '┪',
	make_char_mask(NONE, NONE, DOTT, NONE, BOLD, NONE, BDOT, NONE) => '┪',
	make_char_mask(NONE, NONE, DOTT, NONE, BDOT, NONE, BOLD, NONE) => '┪',
	make_char_mask(BOLD, NONE, THIN, NONE, NONE, NONE, THIN, NONE) => '┝',
	make_char_mask(BOLD, NONE, DOTT, NONE, NONE, NONE, DOTT, NONE) => '┝',
	make_char_mask(BOLD, NONE, THIN, NONE, NONE, NONE, DOTT, NONE) => '┝',
	make_char_mask(BOLD, NONE, DOTT, NONE, NONE, NONE, THIN, NONE) => '┝',
	make_char_mask(BDOT, NONE, THIN, NONE, NONE, NONE, THIN, NONE) => '┝',
	make_char_mask(BDOT, NONE, DOTT, NONE, NONE, NONE, DOTT, NONE) => '┝',
	make_char_mask(BDOT, NONE, THIN, NONE, NONE, NONE, DOTT, NONE) => '┝',
	make_char_mask(BDOT, NONE, DOTT, NONE, NONE, NONE, THIN, NONE) => '┝',
	make_char_mask(THIN, NONE, BOLD, NONE, NONE, NONE, THIN, NONE) => '┞',
	make_char_mask(DOTT, NONE, BOLD, NONE, NONE, NONE, DOTT, NONE) => '┞',
	make_char_mask(THIN, NONE, BOLD, NONE, NONE, NONE, DOTT, NONE) => '┞',
	make_char_mask(DOTT, NONE, BOLD, NONE, NONE, NONE, THIN, NONE) => '┞',
	make_char_mask(THIN, NONE, BDOT, NONE, NONE, NONE, THIN, NONE) => '┞',
	make_char_mask(DOTT, NONE, BDOT, NONE, NONE, NONE, DOTT, NONE) => '┞',
	make_char_mask(THIN, NONE, BDOT, NONE, NONE, NONE, DOTT, NONE) => '┞',
	make_char_mask(DOTT, NONE, BDOT, NONE, NONE, NONE, THIN, NONE) => '┞',
	make_char_mask(THIN, NONE, THIN, NONE, NONE, NONE, BOLD, NONE) => '┟',
	make_char_mask(DOTT, NONE, DOTT, NONE, NONE, NONE, BOLD, NONE) => '┟',
	make_char_mask(THIN, NONE, DOTT, NONE, NONE, NONE, BOLD, NONE) => '┟',
	make_char_mask(DOTT, NONE, THIN, NONE, NONE, NONE, BOLD, NONE) => '┟',
	make_char_mask(THIN, NONE, THIN, NONE, NONE, NONE, BDOT, NONE) => '┟',
	make_char_mask(DOTT, NONE, DOTT, NONE, NONE, NONE, BDOT, NONE) => '┟',
	make_char_mask(THIN, NONE, DOTT, NONE, NONE, NONE, BDOT, NONE) => '┟',
	make_char_mask(DOTT, NONE, THIN, NONE, NONE, NONE, BDOT, NONE) => '┟',
	make_char_mask(THIN, NONE, BOLD, NONE, NONE, NONE, BOLD, NONE) => '┠',
	make_char_mask(THIN, NONE, BDOT, NONE, NONE, NONE, BDOT, NONE) => '┠',
	make_char_mask(THIN, NONE, BOLD, NONE, NONE, NONE, BDOT, NONE) => '┠',
	make_char_mask(THIN, NONE, BDOT, NONE, NONE, NONE, BOLD, NONE) => '┠',
	make_char_mask(DOTT, NONE, BOLD, NONE, NONE, NONE, BOLD, NONE) => '┠',
	make_char_mask(DOTT, NONE, BDOT, NONE, NONE, NONE, BDOT, NONE) => '┠',
	make_char_mask(DOTT, NONE, BOLD, NONE, NONE, NONE, BDOT, NONE) => '┠',
	make_char_mask(DOTT, NONE, BDOT, NONE, NONE, NONE, BOLD, NONE) => '┠',
	make_char_mask(BOLD, NONE, BOLD, NONE, NONE, NONE, THIN, NONE) => '┡',
	make_char_mask(BDOT, NONE, BDOT, NONE, NONE, NONE, THIN, NONE) => '┡',
	make_char_mask(BOLD, NONE, BDOT, NONE, NONE, NONE, THIN, NONE) => '┡',
	make_char_mask(BDOT, NONE, BOLD, NONE, NONE, NONE, THIN, NONE) => '┡',
	make_char_mask(BOLD, NONE, BOLD, NONE, NONE, NONE, DOTT, NONE) => '┡',
	make_char_mask(BDOT, NONE, BDOT, NONE, NONE, NONE, DOTT, NONE) => '┡',
	make_char_mask(BOLD, NONE, BDOT, NONE, NONE, NONE, DOTT, NONE) => '┡',
	make_char_mask(BDOT, NONE, BOLD, NONE, NONE, NONE, DOTT, NONE) => '┡',
	make_char_mask(BOLD, NONE, THIN, NONE, NONE, NONE, BOLD, NONE) => '┢',
	make_char_mask(BDOT, NONE, THIN, NONE, NONE, NONE, BDOT, NONE) => '┢',
	make_char_mask(BOLD, NONE, THIN, NONE, NONE, NONE, BDOT, NONE) => '┢',
	make_char_mask(BDOT, NONE, THIN, NONE, NONE, NONE, BOLD, NONE) => '┢',
	make_char_mask(BOLD, NONE, DOTT, NONE, NONE, NONE, BOLD, NONE) => '┢',
	make_char_mask(BDOT, NONE, DOTT, NONE, NONE, NONE, BDOT, NONE) => '┢',
	make_char_mask(BOLD, NONE, DOTT, NONE, NONE, NONE, BDOT, NONE) => '┢',
	make_char_mask(BDOT, NONE, DOTT, NONE, NONE, NONE, BOLD, NONE) => '┢',
	make_char_mask(THIN, NONE, DOBL, NONE, THIN, NONE, NONE, NONE) => '╨',
	make_char_mask(DOTT, NONE, DOBL, NONE, DOTT, NONE, NONE, NONE) => '╨',
	make_char_mask(THIN, NONE, DOBL, NONE, DOTT, NONE, NONE, NONE) => '╨',
	make_char_mask(DOTT, NONE, DOBL, NONE, THIN, NONE, NONE, NONE) => '╨',
	make_char_mask(DOBL, NONE, THIN, NONE, DOBL, NONE, NONE, NONE) => '╧',
	make_char_mask(DOBL, NONE, DOTT, NONE, DOBL, NONE, NONE, NONE) => '╧',
	make_char_mask(THIN, NONE, NONE, NONE, THIN, NONE, DOBL, NONE) => '╥',
	make_char_mask(DOTT, NONE, NONE, NONE, DOTT, NONE, DOBL, NONE) => '╥',
	make_char_mask(THIN, NONE, NONE, NONE, DOTT, NONE, DOBL, NONE) => '╥',
	make_char_mask(DOTT, NONE, NONE, NONE, THIN, NONE, DOBL, NONE) => '╥',
	make_char_mask(DOBL, NONE, NONE, NONE, DOBL, NONE, THIN, NONE) => '╤',
	make_char_mask(DOBL, NONE, NONE, NONE, DOBL, NONE, DOTT, NONE) => '╤',
	make_char_mask(NONE, NONE, DOBL, NONE, THIN, NONE, DOBL, NONE) => '╢',
	make_char_mask(NONE, NONE, DOBL, NONE, DOTT, NONE, DOBL, NONE) => '╢',
	make_char_mask(NONE, NONE, THIN, NONE, DOBL, NONE, THIN, NONE) => '╡',
	make_char_mask(NONE, NONE, DOTT, NONE, DOBL, NONE, DOTT, NONE) => '╡',
	make_char_mask(NONE, NONE, THIN, NONE, DOBL, NONE, DOTT, NONE) => '╡',
	make_char_mask(NONE, NONE, DOTT, NONE, DOBL, NONE, THIN, NONE) => '╡',
	make_char_mask(THIN, NONE, DOBL, NONE, NONE, NONE, DOBL, NONE) => '╟',
	make_char_mask(DOTT, NONE, DOBL, NONE, NONE, NONE, DOBL, NONE) => '╟',
	make_char_mask(DOBL, NONE, THIN, NONE, NONE, NONE, THIN, NONE) => '╞',
	make_char_mask(DOBL, NONE, DOTT, NONE, NONE, NONE, DOTT, NONE) => '╞',
	make_char_mask(DOBL, NONE, THIN, NONE, NONE, NONE, DOTT, NONE) => '╞',
	make_char_mask(DOBL, NONE, DOTT, NONE, NONE, NONE, THIN, NONE) => '╞',
	make_char_mask(NONE, NONE, THIN, NONE, THIN, NONE, THIN, NONE) => '┤',
	make_char_mask(NONE, NONE, DOTT, NONE, DOTT, NONE, DOTT, NONE) => '┤',
	make_char_mask(NONE, NONE, THIN, NONE, DOTT, NONE, DOTT, NONE) => '┤',
	make_char_mask(NONE, NONE, DOTT, NONE, THIN, NONE, DOTT, NONE) => '┤',
	make_char_mask(NONE, NONE, DOTT, NONE, DOTT, NONE, THIN, NONE) => '┤',
	make_char_mask(NONE, NONE, DOTT, NONE, THIN, NONE, THIN, NONE) => '┤',
	make_char_mask(NONE, NONE, THIN, NONE, DOTT, NONE, THIN, NONE) => '┤',
	make_char_mask(NONE, NONE, THIN, NONE, THIN, NONE, DOTT, NONE) => '┤',
	make_char_mask(THIN, NONE, THIN, NONE, NONE, NONE, THIN, NONE) => '├',
	make_char_mask(DOTT, NONE, DOTT, NONE, NONE, NONE, DOTT, NONE) => '├',
	make_char_mask(THIN, NONE, DOTT, NONE, NONE, NONE, DOTT, NONE) => '├',
	make_char_mask(DOTT, NONE, THIN, NONE, NONE, NONE, DOTT, NONE) => '├',
	make_char_mask(DOTT, NONE, DOTT, NONE, NONE, NONE, THIN, NONE) => '├',
	make_char_mask(DOTT, NONE, THIN, NONE, NONE, NONE, THIN, NONE) => '├',
	make_char_mask(THIN, NONE, DOTT, NONE, NONE, NONE, THIN, NONE) => '├',
	make_char_mask(THIN, NONE, THIN, NONE, NONE, NONE, DOTT, NONE) => '├',
	make_char_mask(THIN, NONE, NONE, NONE, THIN, NONE, THIN, NONE) => '┬',
	make_char_mask(DOTT, NONE, NONE, NONE, DOTT, NONE, DOTT, NONE) => '┬',
	make_char_mask(THIN, NONE, NONE, NONE, DOTT, NONE, DOTT, NONE) => '┬',
	make_char_mask(DOTT, NONE, NONE, NONE, THIN, NONE, DOTT, NONE) => '┬',
	make_char_mask(DOTT, NONE, NONE, NONE, DOTT, NONE, THIN, NONE) => '┬',
	make_char_mask(DOTT, NONE, NONE, NONE, THIN, NONE, THIN, NONE) => '┬',
	make_char_mask(THIN, NONE, NONE, NONE, DOTT, NONE, THIN, NONE) => '┬',
	make_char_mask(THIN, NONE, NONE, NONE, THIN, NONE, DOTT, NONE) => '┬',
	make_char_mask(THIN, NONE, THIN, NONE, THIN, NONE, NONE, NONE) => '┴',
	make_char_mask(DOTT, NONE, DOTT, NONE, DOTT, NONE, NONE, NONE) => '┴',
	make_char_mask(THIN, NONE, DOTT, NONE, DOTT, NONE, NONE, NONE) => '┴',
	make_char_mask(DOTT, NONE, THIN, NONE, DOTT, NONE, NONE, NONE) => '┴',
	make_char_mask(DOTT, NONE, DOTT, NONE, THIN, NONE, NONE, NONE) => '┴',
	make_char_mask(DOTT, NONE, THIN, NONE, THIN, NONE, NONE, NONE) => '┴',
	make_char_mask(THIN, NONE, DOTT, NONE, THIN, NONE, NONE, NONE) => '┴',
	make_char_mask(THIN, NONE, THIN, NONE, DOTT, NONE, NONE, NONE) => '┴',
	make_char_mask(NONE, NONE, BOLD, NONE, BOLD, NONE, BOLD, NONE) => '┫',
	make_char_mask(NONE, NONE, BDOT, NONE, BDOT, NONE, BDOT, NONE) => '┫',
	make_char_mask(NONE, NONE, BOLD, NONE, BDOT, NONE, BDOT, NONE) => '┫',
	make_char_mask(NONE, NONE, BDOT, NONE, BOLD, NONE, BDOT, NONE) => '┫',
	make_char_mask(NONE, NONE, BDOT, NONE, BDOT, NONE, BOLD, NONE) => '┫',
	make_char_mask(NONE, NONE, BDOT, NONE, BOLD, NONE, BOLD, NONE) => '┫',
	make_char_mask(NONE, NONE, BOLD, NONE, BDOT, NONE, BOLD, NONE) => '┫',
	make_char_mask(NONE, NONE, BOLD, NONE, BOLD, NONE, BDOT, NONE) => '┫',
	make_char_mask(BOLD, NONE, BOLD, NONE, NONE, NONE, BOLD, NONE) => '┣',
	make_char_mask(BDOT, NONE, BDOT, NONE, NONE, NONE, BDOT, NONE) => '┣',
	make_char_mask(BOLD, NONE, BDOT, NONE, NONE, NONE, BDOT, NONE) => '┣',
	make_char_mask(BDOT, NONE, BOLD, NONE, NONE, NONE, BDOT, NONE) => '┣',
	make_char_mask(BDOT, NONE, BDOT, NONE, NONE, NONE, BOLD, NONE) => '┣',
	make_char_mask(BDOT, NONE, BOLD, NONE, NONE, NONE, BOLD, NONE) => '┣',
	make_char_mask(BOLD, NONE, BDOT, NONE, NONE, NONE, BOLD, NONE) => '┣',
	make_char_mask(BOLD, NONE, BOLD, NONE, NONE, NONE, BDOT, NONE) => '┣',
	make_char_mask(BOLD, NONE, NONE, NONE, BOLD, NONE, BOLD, NONE) => '┳',
	make_char_mask(BDOT, NONE, NONE, NONE, BDOT, NONE, BDOT, NONE) => '┳',
	make_char_mask(BOLD, NONE, NONE, NONE, BDOT, NONE, BDOT, NONE) => '┳',
	make_char_mask(BDOT, NONE, NONE, NONE, BOLD, NONE, BDOT, NONE) => '┳',
	make_char_mask(BDOT, NONE, NONE, NONE, BDOT, NONE, BOLD, NONE) => '┳',
	make_char_mask(BDOT, NONE, NONE, NONE, BOLD, NONE, BOLD, NONE) => '┳',
	make_char_mask(BOLD, NONE, NONE, NONE, BDOT, NONE, BOLD, NONE) => '┳',
	make_char_mask(BOLD, NONE, NONE, NONE, BOLD, NONE, BDOT, NONE) => '┳',
	make_char_mask(BOLD, NONE, BOLD, NONE, BOLD, NONE, NONE, NONE) => '┻',
	make_char_mask(BDOT, NONE, BDOT, NONE, BDOT, NONE, NONE, NONE) => '┻',
	make_char_mask(BOLD, NONE, BDOT, NONE, BDOT, NONE, NONE, NONE) => '┻',
	make_char_mask(BDOT, NONE, BOLD, NONE, BDOT, NONE, NONE, NONE) => '┻',
	make_char_mask(BDOT, NONE, BDOT, NONE, BOLD, NONE, NONE, NONE) => '┻',
	make_char_mask(BDOT, NONE, BOLD, NONE, BOLD, NONE, NONE, NONE) => '┻',
	make_char_mask(BOLD, NONE, BDOT, NONE, BOLD, NONE, NONE, NONE) => '┻',
	make_char_mask(BOLD, NONE, BOLD, NONE, BDOT, NONE, NONE, NONE) => '┻',
	make_char_mask(NONE, NONE, DOBL, NONE, DOBL, NONE, DOBL, NONE) => '╣',
	make_char_mask(DOBL, NONE, DOBL, NONE, NONE, NONE, DOBL, NONE) => '╠',
	make_char_mask(DOBL, NONE, NONE, NONE, DOBL, NONE, DOBL, NONE) => '╦',
	make_char_mask(DOBL, NONE, DOBL, NONE, DOBL, NONE, NONE, NONE) => '╩',
	make_char_mask(NONE, NONE, DOBL, NONE, THIN, NONE, NONE, NONE) => '╜',
	make_char_mask(NONE, NONE, DOBL, NONE, DOTT, NONE, NONE, NONE) => '╜',
	make_char_mask(NONE, NONE, THIN, NONE, DOBL, NONE, NONE, NONE) => '╛',
	make_char_mask(NONE, NONE, DOTT, NONE, DOBL, NONE, NONE, NONE) => '╛',
	make_char_mask(THIN, NONE, DOBL, NONE, NONE, NONE, NONE, NONE) => '╙',
	make_char_mask(DOTT, NONE, DOBL, NONE, NONE, NONE, NONE, NONE) => '╙',
	make_char_mask(DOBL, NONE, THIN, NONE, NONE, NONE, NONE, NONE) => '╘',
	make_char_mask(DOBL, NONE, DOTT, NONE, NONE, NONE, NONE, NONE) => '╘',
	make_char_mask(NONE, NONE, NONE, NONE, THIN, NONE, DOBL, NONE) => '╖',
	make_char_mask(NONE, NONE, NONE, NONE, DOTT, NONE, DOBL, NONE) => '╖',
	make_char_mask(NONE, NONE, NONE, NONE, DOBL, NONE, THIN, NONE) => '╕',
	make_char_mask(NONE, NONE, NONE, NONE, DOBL, NONE, DOTT, NONE) => '╕',
	make_char_mask(THIN, NONE, NONE, NONE, NONE, NONE, DOBL, NONE) => '╓',
	make_char_mask(DOTT, NONE, NONE, NONE, NONE, NONE, DOBL, NONE) => '╓',
	make_char_mask(DOBL, NONE, NONE, NONE, NONE, NONE, THIN, NONE) => '╒',
	make_char_mask(DOBL, NONE, NONE, NONE, NONE, NONE, DOTT, NONE) => '╒',
	make_char_mask(BOLD, NONE, NONE, NONE, NONE, NONE, THIN, NONE) => '┍',
	make_char_mask(BDOT, NONE, NONE, NONE, NONE, NONE, DOTT, NONE) => '┍',
	make_char_mask(BOLD, NONE, NONE, NONE, NONE, NONE, DOTT, NONE) => '┍',
	make_char_mask(BDOT, NONE, NONE, NONE, NONE, NONE, THIN, NONE) => '┍',
	make_char_mask(THIN, NONE, NONE, NONE, NONE, NONE, BOLD, NONE) => '┎',
	make_char_mask(DOTT, NONE, NONE, NONE, NONE, NONE, BDOT, NONE) => '┎',
	make_char_mask(DOTT, NONE, NONE, NONE, NONE, NONE, BOLD, NONE) => '┎',
	make_char_mask(THIN, NONE, NONE, NONE, NONE, NONE, BDOT, NONE) => '┎',
	make_char_mask(NONE, NONE, NONE, NONE, BOLD, NONE, THIN, NONE) => '┑',
	make_char_mask(NONE, NONE, NONE, NONE, BDOT, NONE, DOTT, NONE) => '┑',
	make_char_mask(NONE, NONE, NONE, NONE, BDOT, NONE, THIN, NONE) => '┑',
	make_char_mask(NONE, NONE, NONE, NONE, BOLD, NONE, DOTT, NONE) => '┑',
	make_char_mask(NONE, NONE, NONE, NONE, THIN, NONE, BOLD, NONE) => '┒',
	make_char_mask(NONE, NONE, NONE, NONE, DOTT, NONE, BDOT, NONE) => '┒',
	make_char_mask(NONE, NONE, NONE, NONE, THIN, NONE, BDOT, NONE) => '┒',
	make_char_mask(NONE, NONE, NONE, NONE, DOTT, NONE, BOLD, NONE) => '┒',
	make_char_mask(BOLD, NONE, THIN, NONE, NONE, NONE, NONE, NONE) => '┕',
	make_char_mask(BDOT, NONE, DOTT, NONE, NONE, NONE, NONE, NONE) => '┕',
	make_char_mask(BDOT, NONE, THIN, NONE, NONE, NONE, NONE, NONE) => '┕',
	make_char_mask(BOLD, NONE, DOTT, NONE, NONE, NONE, NONE, NONE) => '┕',
	make_char_mask(THIN, NONE, BOLD, NONE, NONE, NONE, NONE, NONE) => '┖',
	make_char_mask(DOTT, NONE, BDOT, NONE, NONE, NONE, NONE, NONE) => '┖',
	make_char_mask(DOTT, NONE, BOLD, NONE, NONE, NONE, NONE, NONE) => '┖',
	make_char_mask(THIN, NONE, BDOT, NONE, NONE, NONE, NONE, NONE) => '┖',
	make_char_mask(NONE, NONE, THIN, NONE, BOLD, NONE, NONE, NONE) => '┙',
	make_char_mask(NONE, NONE, DOTT, NONE, BDOT, NONE, NONE, NONE) => '┙',
	make_char_mask(NONE, NONE, THIN, NONE, BDOT, NONE, NONE, NONE) => '┙',
	make_char_mask(NONE, NONE, DOTT, NONE, BOLD, NONE, NONE, NONE) => '┙',
	make_char_mask(NONE, NONE, BOLD, NONE, THIN, NONE, NONE, NONE) => '┚',
	make_char_mask(NONE, NONE, BDOT, NONE, DOTT, NONE, NONE, NONE) => '┚',
	make_char_mask(NONE, NONE, BOLD, NONE, DOTT, NONE, NONE, NONE) => '┚',
	make_char_mask(NONE, NONE, BDOT, NONE, THIN, NONE, NONE, NONE) => '┚',
	make_char_mask(THIN, NONE, NONE, NONE, NONE, NONE, THIN, NONE) => '╭',
	make_char_mask(DOTT, NONE, NONE, NONE, NONE, NONE, DOTT, NONE) => '╭',
	make_char_mask(THIN, NONE, NONE, NONE, NONE, NONE, DOTT, NONE) => '╭',
	make_char_mask(DOTT, NONE, NONE, NONE, NONE, NONE, THIN, NONE) => '╭',
	make_char_mask(NONE, NONE, NONE, NONE, THIN, NONE, THIN, NONE) => '╮',
	make_char_mask(NONE, NONE, NONE, NONE, DOTT, NONE, DOTT, NONE) => '╮',
	make_char_mask(NONE, NONE, NONE, NONE, THIN, NONE, DOTT, NONE) => '╮',
	make_char_mask(NONE, NONE, NONE, NONE, DOTT, NONE, THIN, NONE) => '╮',
	make_char_mask(NONE, NONE, THIN, NONE, THIN, NONE, NONE, NONE) => '╯',
	make_char_mask(NONE, NONE, DOTT, NONE, DOTT, NONE, NONE, NONE) => '╯',
	make_char_mask(NONE, NONE, THIN, NONE, DOTT, NONE, NONE, NONE) => '╯',
	make_char_mask(NONE, NONE, DOTT, NONE, THIN, NONE, NONE, NONE) => '╯',
	make_char_mask(THIN, NONE, THIN, NONE, NONE, NONE, NONE, NONE) => '╰',
	make_char_mask(DOTT, NONE, DOTT, NONE, NONE, NONE, NONE, NONE) => '╰',
	make_char_mask(THIN, NONE, DOTT, NONE, NONE, NONE, NONE, NONE) => '╰',
	make_char_mask(DOTT, NONE, THIN, NONE, NONE, NONE, NONE, NONE) => '╰',
	make_char_mask(BOLD, NONE, NONE, NONE, NONE, NONE, BOLD, NONE) => '┏',
	make_char_mask(BDOT, NONE, NONE, NONE, NONE, NONE, BDOT, NONE) => '┏',
	make_char_mask(BOLD, NONE, NONE, NONE, NONE, NONE, BDOT, NONE) => '┏',
	make_char_mask(BDOT, NONE, NONE, NONE, NONE, NONE, BOLD, NONE) => '┏',
	make_char_mask(NONE, NONE, NONE, NONE, BOLD, NONE, BOLD, NONE) => '┓',
	make_char_mask(NONE, NONE, NONE, NONE, BDOT, NONE, BDOT, NONE) => '┓',
	make_char_mask(NONE, NONE, NONE, NONE, BOLD, NONE, BDOT, NONE) => '┓',
	make_char_mask(NONE, NONE, NONE, NONE, BDOT, NONE, BOLD, NONE) => '┓',
	make_char_mask(NONE, NONE, BOLD, NONE, BOLD, NONE, NONE, NONE) => '┛',
	make_char_mask(NONE, NONE, BDOT, NONE, BDOT, NONE, NONE, NONE) => '┛',
	make_char_mask(NONE, NONE, BOLD, NONE, BDOT, NONE, NONE, NONE) => '┛',
	make_char_mask(NONE, NONE, BDOT, NONE, BOLD, NONE, NONE, NONE) => '┛',
	make_char_mask(BOLD, NONE, BOLD, NONE, NONE, NONE, NONE, NONE) => '┗',
	make_char_mask(BDOT, NONE, BDOT, NONE, NONE, NONE, NONE, NONE) => '┗',
	make_char_mask(BOLD, NONE, BDOT, NONE, NONE, NONE, NONE, NONE) => '┗',
	make_char_mask(BDOT, NONE, BOLD, NONE, NONE, NONE, NONE, NONE) => '┗',
	make_char_mask(DOBL, NONE, NONE, NONE, NONE, NONE, DOBL, NONE) => '╔',
	make_char_mask(NONE, NONE, NONE, NONE, DOBL, NONE, DOBL, NONE) => '╗',
	make_char_mask(NONE, NONE, DOBL, NONE, DOBL, NONE, NONE, NONE) => '╝',
	make_char_mask(DOBL, NONE, DOBL, NONE, NONE, NONE, NONE, NONE) => '╚',
	make_char_mask(NONE, ASCI, NONE, ASCI, NONE, ASCI, NONE, ASCI) => 'X',
	make_char_mask(NONE, THIN, NONE, THIN, NONE, THIN, NONE, THIN) => '╳',
	make_char_mask(NONE, THIN, NONE, DOTT, NONE, DOTT, NONE, DOTT) => '╳',
	make_char_mask(NONE, DOTT, NONE, THIN, NONE, DOTT, NONE, DOTT) => '╳',
	make_char_mask(NONE, DOTT, NONE, DOTT, NONE, THIN, NONE, DOTT) => '╳',
	make_char_mask(NONE, DOTT, NONE, DOTT, NONE, DOTT, NONE, THIN) => '╳',
	make_char_mask(NONE, THIN, NONE, THIN, NONE, DOTT, NONE, DOTT) => '╳',
	make_char_mask(NONE, THIN, NONE, DOTT, NONE, THIN, NONE, DOTT) => '╳',
	make_char_mask(NONE, THIN, NONE, DOTT, NONE, DOTT, NONE, THIN) => '╳',
	make_char_mask(NONE, DOTT, NONE, THIN, NONE, THIN, NONE, DOTT) => '╳',
	make_char_mask(NONE, DOTT, NONE, THIN, NONE, DOTT, NONE, THIN) => '╳',
	make_char_mask(NONE, DOTT, NONE, DOTT, NONE, THIN, NONE, THIN) => '╳',
	make_char_mask(NONE, THIN, NONE, THIN, NONE, THIN, NONE, DOTT) => '╳',
	make_char_mask(NONE, THIN, NONE, THIN, NONE, DOTT, NONE, THIN) => '╳',
	make_char_mask(NONE, THIN, NONE, DOTT, NONE, THIN, NONE, THIN) => '╳',
	make_char_mask(NONE, DOTT, NONE, THIN, NONE, THIN, NONE, THIN) => '╳',
	make_char_mask(NONE, DOTT, NONE, DOTT, NONE, DOTT, NONE, DOTT) => '╳',
	) ;

#-----------------------------------------------------------------------------

sub make_char_mask
{
my ($right, $d45, $up, $d135, $left, $d225, $down, $d315) = @_ ;
return ($up << UP_OFFSET)
	| ($right << RIGHT_OFFSET)
	| ($down << DOWN_OFFSET)
	| ($left << LEFT_OFFSET)
	| ($d45 << D45_OFFSET)
	| ($d135 << D135_OFFSET)
	| ($d225 << D225_OFFSET)
	| ($d315 << D315_OFFSET) ;
}

#-----------------------------------------------------------------------------

sub get_char_direction_value
{
my ($chars_list, $offset) = @_;

for my $char (@$chars_list)
	{
	my $value = $CROSS_CHARS_VALUES{$char} // 0 ;
	if ($value != 0)
		{
		my $val = ($value >> $offset) & ATTR_MASK ;
		if ($val != 0)
			{
			return $val;
			}
		}
	}

return 0;
}

#-----------------------------------------------------------------------------

sub cross_get_center_char
{
my ($right, $d45, $up, $d135, $left, $d225, $down, $d315) = @_ ;

my $char_key = (get_char_direction_value($left,  RIGHT_OFFSET) << LEFT_OFFSET)
	| (get_char_direction_value($right, LEFT_OFFSET)  << RIGHT_OFFSET)
	| (get_char_direction_value($up,    DOWN_OFFSET)  << UP_OFFSET)
	| (get_char_direction_value($down,  UP_OFFSET)    << DOWN_OFFSET)
	| (get_char_direction_value($d45,   D225_OFFSET)  << D45_OFFSET)
	| (get_char_direction_value($d135,  D315_OFFSET)  << D135_OFFSET)
	| (get_char_direction_value($d225,  D45_OFFSET)   << D225_OFFSET)
	| (get_char_direction_value($d315,  D135_OFFSET)  << D315_OFFSET) ;

return $VALUES_TO_CROSS_CHAR{$char_key} // '' ;
}

#-----------------------------------------------------------------------------

sub get_cross_mode_overlays
{
my ($zbuffer) = @_;

my @overlays ;

return @overlays unless(defined $zbuffer->{intersecting_elements}) ;

my $cross_zbuffer = Clone::clone($zbuffer) ;

while (my ($coordinate, $char_stacks) = each %{ $cross_zbuffer->{intersecting_elements} })
	{
	my $cross_array ;
	my $char_count = 0 ;
	for my $char (@$char_stacks)
		{
		last unless exists $CROSS_CHARS_VALUES{$char};
		push @{$cross_array}, $char;
		$char_count++;
		}
	if($char_count >= 2)
		{
		$cross_zbuffer->{intersecting_elements}{$coordinate} = $cross_array ;
		}
	else
		{
		delete $cross_zbuffer->{intersecting_elements}{$coordinate} ;
		}
	}

while( my($coordinate, $elements) = each $cross_zbuffer->{intersecting_elements}->%*)
	{
	my ($Y, $X) = split ';', $coordinate ;
	my $neighbors_stack = $cross_zbuffer->get_neighbors_stack($coordinate) ;
	
	my ($char_315, $up, $char_45, $right, $char_135, $down, $char_225, $left) = 
		($neighbors_stack->{($Y-1) . ';' . ($X-1)} // [],
		$neighbors_stack->{($Y-1) . ';' . $X}      // [],
		$neighbors_stack->{($Y-1) . ';' . ($X+1)}  // [],
		$neighbors_stack->{$Y . ';' . ($X+1)}      // [],
		$neighbors_stack->{($Y+1) . ';' . ($X+1)}  // [],
		$neighbors_stack->{($Y+1) . ';' . $X}      // [],
		$neighbors_stack->{($Y+1) . ';' . ($X-1)}  // [],
		$neighbors_stack->{$Y . ';' . ($X-1)}      // []) ;
		
	my $center_char = cross_get_center_char($right, [], $up, [], $left, [], $down, []) ;
	if ($center_char eq '')
		{
		$center_char = cross_get_center_char([], $char_45, [], $char_135, [], $char_225, [], $char_315) ;
		}

	if ($center_char ne '')
		{
		push @overlays, [$X, $Y, $center_char] ;
		}
	}
return @overlays ;
}

#-----------------------------------------------------------------------------

1 ;

