#!/usr/bin/env perl
use strict;
use warnings;

use Gtk3 -init;
use Glib::Object::Introspection;
use Glib qw(TRUE FALSE);

use App::Asciio::GTK::Asciio::TabManager ;

my $window = Gtk3::Window->new('toplevel') ;
$window->set_title('Asciio') ;
$window->set_default_size(600, 400) ;
my $tab_manager =  App::Asciio::GTK::Asciio::TabManager->new() ;

$window->add($tab_manager->get_widget()) ;

$window->signal_connect
	(
	destroy => sub
		{
		Gtk3::main_quit() ;
		}
	) ;

$window->show_all() ;

# $window->signal_connect
# 	(
# 	'key-press-event' => sub
# 				{
# 				my ($widget, $event) = @_ ;
# 				$widget->grab_focus() ;
# 				# App::Asciio::GTK::Asciio::button_press_event(undef, $event, $self) ;
# 				print"in main window key-press-event\n" ;
# 				return TRUE ;
# 				}
# 	) ;

Gtk3::main() ;

