#!/bin/env perl

use strict ; use warnings ;
use JSON ;
use Data::TreeDumper ;

my $title       = $ARGV[0] // '' ;
my $x           = $ARGV[1] // 0 ;
my $y           = $ARGV[2] // 0 ;
my $box         = $ARGV[3] // '' ;
my $start_level = $ARGV[4] // 1 ;

undef $/ ;
my $json = <STDIN> ;
my $data = from_json $json ;
my $dtd  = DumpTree $data, $title, DISPLAY_ADDRESS => 0, START_LEVEL => $start_level ;

my $type = $box eq 'box' ? 'new_box' : 'new_text' ;

print  "use App::Asciio::Scripting ;\n" ;
printf "add '%s', $type(TEXT_ONLY =>'$dtd'), $x, $y ;", $title ; 

#vim: set ft=perl :
