#!/usr/bin/env perl
use strict;
use warnings;

use Gtk3 -init;
use Glib::Object::Introspection;

use App::Asciio::GTK::Asciio::TabManager ;

my $window = Gtk3::Window->new('toplevel') ;
$window->set_title('Asciior') ;
$window->set_default_size(600, 400) ;

my $tab_manager =  App::Asciio::GTK::Asciio::TabManager->new() ;

$window->add($tab_manager->get_widget()) ;

$window->signal_connect
	(
	destroy => sub
		{
		Gtk3::main_quit() ;
		}
	) ;

$window->show_all() ;

Gtk3::main() ;

