#!/bin/env perl

use strict; use warnings;

use File::Slurp ;
use App::Asciio::Scripting ;

binmode(STDOUT) ;
my $pos = -1 ;

if (-p STDIN || -f STDIN) 
	{
	my $boxed = get_option('TEXT_TO_ASCIIO_BOX_INPUT') ? 1 : 0 ;
	my $regex = get_option('TEXT_TO_ASCIIO_SEPARATOR') // '\n' ;
	
	local $/;
	for my $line (split $regex, <STDIN>)
		{
		$pos++ ;
		
		add "box$pos", new_box
				(
				TEXT_ONLY => $line,
				BOX_TYPE =>
					[
					[$boxed, 'top',              '.', '-',  '.', 1, ],
					[0     , 'title separator',  '|', '-',  '|', 1, ],
					[$boxed, 'body separator',  '| ', '|', ' |', 1, ],
					[$boxed, 'bottom',          '\'', '-', '\'', 1, ],
					[$boxed, 'fill-character',  '',   ' ', '',   1, ],
					],
				),  $pos,  $pos ;
		}
	
	print to_asciio() ;
	}
else
	{
	die "usage:\n\ttext_to_asciio output_file_name text_file_to import text_file_to import ...\n\tcommand | text_to_asciio > file.asciio" if @ARGV < 2 ;
	
	my $output_file_name = shift @ARGV ;
	
	for my $text_to_import_file (@ARGV)
		{
		$pos++ ;
		
		add "box$pos", new_box
				(
				TEXT_ONLY => scalar read_file($text_to_import_file),
				BOX_TYPE =>
					[
					[0, 'top',              '.', '-',  '.', 1, ],
					[0, 'title separator',  '|', '-',  '|', 1, ],
					[0, 'body separator',  '| ', '|', ' |', 1, ],
					[0, 'bottom',          '\'', '-', '\'', 1, ],
					[0, 'fill-character',  '',   ' ', '',   1, ],
					],
				),  $pos,  $pos ;
		}
	
	save_to "$output_file_name.asciio" ;
	}
